<?php
/***************************************************************************
*                                                                          *
*   (c) 2004 Vladimir V. Kalynyak, Alexey V. Vinokurov, Ilya M. Shalnev    *
*                                                                          *
* This  is  commercial  software,  only  users  who have purchased a valid *
* license  and  accept  to the terms of the  License Agreement can install *
* and use this program.                                                    *
*                                                                          *
****************************************************************************
* PLEASE READ THE FULL TEXT  OF THE SOFTWARE  LICENSE   AGREEMENT  IN  THE *
* "copyright.txt" FILE PROVIDED WITH THIS DISTRIBUTION PACKAGE.            *
****************************************************************************/

// rus_build_edost dbazhenov

$services = array(
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '301',
        'sp_file' => '',
        'description' => 'EDOST: Почта России (отправление 1-го класса)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '302',
        'sp_file' => '',
        'description' => 'EDOST: Почта России (отправление 1-го класса) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '303',
        'sp_file' => '',
        'description' => 'EDOST: Почта России (наземная посылка)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '304',
        'sp_file' => '',
        'description' => 'EDOST: Почта России (наземная посылка) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '305',
        'sp_file' => '',
        'description' => 'EDOST: EMS Почта России',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '306',
        'sp_file' => '',
        'description' => 'EDOST: EMS Почта России со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '309',
        'sp_file' => '',
        'description' => 'EDOST: СПСР Экспресс (пеликан-стандарт)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '310',
        'sp_file' => '',
        'description' => 'EDOST: СПСР Экспресс (пеликан-стандарт) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '311',
        'sp_file' => '',
        'description' => 'EDOST: СДЭК (экспресс дверь-дверь)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '312',
        'sp_file' => '',
        'description' => 'EDOST: СДЭК (экспресс дверь-дверь) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '313',
        'sp_file' => '',
        'description' => 'EDOST: СДЭК (экспресс склад-склад)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '314',
        'sp_file' => '',
        'description' => 'EDOST: СДЭК (экспресс склад-склад) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '315',
        'sp_file' => '',
        'description' => 'EDOST: СДЭК (экспресс склад-дверь)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '316',
        'sp_file' => '',
        'description' => 'EDOST: СДЭК (экспресс склад-дверь) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '317',
        'sp_file' => '',
        'description' => 'EDOST: СДЭК (экспресс дверь-склад)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '318',
        'sp_file' => '',
        'description' => 'EDOST: СДЭК (экспресс дверь-склад) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '319',
        'sp_file' => '',
        'description' => 'EDOST: СДЭК (супер-экспресс)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '320',
        'sp_file' => '',
        'description' => 'EDOST: СДЭК (супер-экспресс) со страховкой',
    ),

    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '321',
        'sp_file' => '',
        'description' => 'EDOST: DHL Express (экспресс 18:00)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '322',
        'sp_file' => '',
        'description' => 'EDOST: DHL Express (экспресс 18:00) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '323',
        'sp_file' => '',
        'description' => 'EDOST: UPS (Express Saver)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '324',
        'sp_file' => '',
        'description' => 'EDOST: UPS (Express Saver) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '327',
        'sp_file' => '',
        'description' => 'EDOST: ЖелДорЭкспедиция',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '328',
        'sp_file' => '',
        'description' => 'EDOST: ЖелДорЭкспедиция со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '329',
        'sp_file' => '',
        'description' => 'EDOST: Автотрэйдинг',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '330',
        'sp_file' => '',
        'description' => 'EDOST: Автотрэйдинг со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '331',
        'sp_file' => '',
        'description' => 'EDOST: ПЭК',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '332',
        'sp_file' => '',
        'description' => 'EDOST: ПЭК со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '333',
        'sp_file' => '',
        'description' => 'EDOST: СДЭК (международный экспресс)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '334',
        'sp_file' => '',
        'description' => 'EDOST: СДЭК (международный экспресс) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '335',
        'sp_file' => '',
        'description' => 'EDOST: EMS Почта России (международное отправление)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '336',
        'sp_file' => '',
        'description' => 'EDOST: EMS Почта России (международное отправление) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '337',
        'sp_file' => '',
        'description' => 'EDOST: СПСР Экспресс (международное отправление)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '338',
        'sp_file' => '',
        'description' => 'EDOST: СПСР Экспресс (международное отправление) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '339',
        'sp_file' => '',
        'description' => 'EDOST: DHL Express (экспресс за границу)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '340',
        'sp_file' => '',
        'description' => 'EDOST: DHL Express (экспресс за границу) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '341',
        'sp_file' => '',
        'description' => 'EDOST: UPS (международный Express Saver)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '342',
        'sp_file' => '',
        'description' => 'EDOST: UPS (международный Express Saver) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '343',
        'sp_file' => '',
        'description' => 'EDOST: Деловые линии',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '344',
        'sp_file' => '',
        'description' => 'EDOST: Деловые линии со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '345',
        'sp_file' => '',
        'description' => 'EDOST: Мегаполис (бизнес-экспресс дверь-дверь)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '346',
        'sp_file' => '',
        'description' => 'EDOST: Мегаполис (бизнес-экспресс дверь-дверь) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '347',
        'sp_file' => '',
        'description' => 'EDOST: Мегаполис (эконом-экспресс склад-дверь)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '348',
        'sp_file' => '',
        'description' => 'EDOST: Мегаполис (эконом-экспресс склад-дверь) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '349',
        'sp_file' => '',
        'description' => 'EDOST: Гарантпост',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '350',
        'sp_file' => '',
        'description' => 'EDOST: Гарантпост со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '351',
        'sp_file' => '',
        'description' => 'EDOST: Гарантпост (международное отправление)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '352',
        'sp_file' => '',
        'description' => 'EDOST: Гарантпост (международное отправление) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '353',
        'sp_file' => '',
        'description' => 'EDOST: PONY EXPRESS',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '354',
        'sp_file' => '',
        'description' => 'EDOST: PONY EXPRESS со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '355',
        'sp_file' => '',
        'description' => 'EDOST: PONY EXPRESS (международное отправление)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '356',
        'sp_file' => '',
        'description' => 'EDOST: PONY EXPRESS (международное отправление) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '357',
        'sp_file' => '',
        'description' => 'EDOST: PickPoint (постаматы и пункты выдачи)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '358',
        'sp_file' => '',
        'description' => 'EDOST: PickPoint (постаматы и пункты выдачи) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '361',
        'sp_file' => '',
        'description' => 'EDOST: Курьер. Тариф 1',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '363',
        'sp_file' => '',
        'description' => 'EDOST: Курьер. Тариф 2',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '365',
        'sp_file' => '',
        'description' => 'EDOST: Курьер. Тариф 3',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '367',
        'sp_file' => '',
        'description' => 'EDOST: Курьер. Тариф 4',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '369',
        'sp_file' => '',
        'description' => 'EDOST: Самовывоз',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '371',
        'sp_file' => '',
        'description' => 'EDOST: boxberry (до пункта выдачи)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '372',
        'sp_file' => '',
        'description' => 'EDOST: boxberry (до пункта выдачи) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '373',
        'sp_file' => '',
        'description' => 'EDOST: СДЭК (посылка до пункта выдачи)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '374',
        'sp_file' => '',
        'description' => 'EDOST: СДЭК (посылка до пункта выдачи) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '375',
        'sp_file' => '',
        'description' => 'EDOST: СДЭК (посылка курьером до двери)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '376',
        'sp_file' => '',
        'description' => 'EDOST: СДЭК (посылка курьером до двери) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '377',
        'sp_file' => '',
        'description' => 'EDOST: Энергия (авто)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '378',
        'sp_file' => '',
        'description' => 'EDOST: Энергия (авто) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '379',
        'sp_file' => '',
        'description' => 'EDOST: Энергия (жд)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '380',
        'sp_file' => '',
        'description' => 'EDOST: Энергия (жд) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '381',
        'sp_file' => '',
        'description' => 'EDOST: Энергия (авиа)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '382',
        'sp_file' => '',
        'description' => 'EDOST: Энергия (авиа) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '383',
        'sp_file' => '',
        'description' => 'EDOST: Энергия (морем)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '384',
        'sp_file' => '',
        'description' => 'EDOST: Энергия (морем) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '385',
        'sp_file' => '',
        'description' => 'EDOST: boxberry (курьером до двери)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '386',
        'sp_file' => '',
        'description' => 'EDOST: boxberry (курьером до двери) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '387',
        'sp_file' => '',
        'description' => 'EDOST: DPD classic - курьером до двери',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '388',
        'sp_file' => '',
        'description' => 'EDOST: DPD classic - курьером до двери со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '389',
        'sp_file' => '',
        'description' => 'EDOST: DPD consumer - курьером до двери',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '390',
        'sp_file' => '',
        'description' => 'EDOST: DPD consumer - курьером до двери со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '391',
        'sp_file' => '',
        'description' => 'EDOST: DPD parcel - до пункта выдачи',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '392',
        'sp_file' => '',
        'description' => 'EDOST: DPD parcel - до пункта выдачи со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '393',
        'sp_file' => '',
        'description' => 'EDOST: DPD parcel - курьером до двери',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '394',
        'sp_file' => '',
        'description' => 'EDOST: DPD parcel - курьером до двери со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '395',
        'sp_file' => '',
        'description' => 'EDOST: ЖелДорЭкспедиция (до подъезда)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '396',
        'sp_file' => '',
        'description' => 'EDOST: ЖелДорЭкспедиция (до подъезда) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '397',
        'sp_file' => '',
        'description' => 'EDOST: ПЭК (до подъезда)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '398',
        'sp_file' => '',
        'description' => 'EDOST: ПЭК (до подъезда со страховкой)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '399',
        'sp_file' => '',
        'description' => 'EDOST: Автотрэйдинг (до подъезда)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '400',
        'sp_file' => '',
        'description' => 'EDOST: Автотрэйдинг (до подъезда) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '401',
        'sp_file' => '',
        'description' => 'EDOST: Деловые линии (до подъезда)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '402',
        'sp_file' => '',
        'description' => 'EDOST: Деловые линии (до подъезда) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '403',
        'sp_file' => '',
        'description' => 'EDOST: Энергия (авто - до подъезда)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '404',
        'sp_file' => '',
        'description' => 'EDOST: Энергия (авто - до подъезда) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '405',
        'sp_file' => '',
        'description' => 'EDOST: Энергия (жд - до подъезда)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '406',
        'sp_file' => '',
        'description' => 'EDOST: Энергия (жд - до подъезда) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '407',
        'sp_file' => '',
        'description' => 'EDOST: Энергия (авиа - до подъезда)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '408',
        'sp_file' => '',
        'description' => 'EDOST: Энергия (авиа - до подъезда) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '409',
        'sp_file' => '',
        'description' => 'EDOST: Энергия (морем - до подъезда)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '410',
        'sp_file' => '',
        'description' => 'EDOST: Энергия (морем - до подъезда) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '411',
        'sp_file' => '',
        'description' => 'EDOST: Самовывоз (тариф 2)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '412',
        'sp_file' => '',
        'description' => 'EDOST: Самовывоз (тариф 2) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '413',
        'sp_file' => '',
        'description' => 'EDOST: Самовывоз (тариф 3)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '414',
        'sp_file' => '',
        'description' => 'EDOST: Самовывоз (тариф 3) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '415',
        'sp_file' => '',
        'description' => 'EDOST: Самовывоз (тариф 4)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '416',
        'sp_file' => '',
        'description' => 'EDOST: Самовывоз (тариф 4) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '417',
        'sp_file' => '',
        'description' => 'EDOST: РАТЭК (до терминала)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '418',
        'sp_file' => '',
        'description' => 'EDOST: РАТЭК (до терминала) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '419',
        'sp_file' => '',
        'description' => 'EDOST: РАТЭК (до подъезда)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '420',
        'sp_file' => '',
        'description' => 'EDOST: РАТЭК (до подъезда) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '421',
        'sp_file' => '',
        'description' => 'EDOST: Почта России (посылка онлайн)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '422',
        'sp_file' => '',
        'description' => 'EDOST: Почта России (посылка онлайн) со страховкой',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '423',
        'sp_file' => '',
        'description' => 'EDOST: Почта России (курьер онлайн)',
    ),
    array(
        'status' => 'A',
        'module' => 'edost',
        'code' => '424',
        'sp_file' => '',
        'description' => 'EDOST: Почта России (курьер онлайн) со страховкой',
    ),
);

return $services;
